ktor:
  development: true
  deployment:
    port: 8080
    shutdown:
      url: "/shutdown"
  application:
    modules:
      - dev.reprator.ApplicationKt.module

storage:
  driverClassName: "org.postgresql.Driver"
  databaseName: "khatabook"
  portNumber: 5432
  serverName: localhost
  ehcacheFilePath: build/ehcache

jwt:
  secret: "secret"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/hello"
  realm: "Access to 'hello'"

khatabook:
  splash:
    dir: "splashFileDirectory"
