ktor:
  development: true
  deployment:
    port: "$PORT:8081"
    shutdown:
      url: "/shutdown"
  application:
    modules:
      - dev.reprator.ApplicationKt.module


storage:
  driverClassName: "org.postgresql.Driver"
  databaseName: "$DATABASE_NAME:khatabook"
  portNumber: "$DATABASE_PORT:5432"
  serverName: "$DATABASE_SERVER_NAME:localhost"
  userName: "$DATABASE_USERNAME:postgres"
  password: "$DATABASE_PASSWORD:vikram90#"


secrets:
  phone:
      apiKey: "dQzSARrkyBgkLpNKLnswaqnktfC2EvrB7IwiPCLbIUUKJtIj"
      userId: "Reprator"


jwt:
  secret: "RepratorKhataBookSecret"
  issuer: "khataBookIssuer"
  audience: "khatabookAudience"
  realm: "khatabookRealm"
  realmRole: "khatabookRealmRole"


khatabook:
  splash:
    dir: "splashFileDirectory"
