name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v3

      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle compile and Run tests
        run: gradlew clean test

      - name: Report on tests
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test results
          path: build/test-results/*.xml
          reporter: java-junit